language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_script:
  - php -m
  - php --info | grep -i 'intl\|pcre'

script: phpunit --debug

notifications:
    email:
        on_success: never
